name: Docker Image CI

on:
  push:
    branches: 
    - master 
    - gnome
  pull_request:
    branches: 
    - master 
    - gnome
  schedule:
  - cron: "0 2 * * 1-5"
  
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag mygentoo:release-master
      
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true # default: false
        tag_name: release-master # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Release Assets
      run: |
        set -x
        assets=()
        for asset in checksums.txt mygentoo:release-master; do
        assets+=("-a" "$asset")
        done
        tag_name="release-master"
        hub release create  "${assets[@]}" \
        -m "Release $tag_name" \
        -m "This release was automatically created by the Git Actions workflow corresponding to directory .github in the repository." \
        -m "The output are a checksum file and a Docker image for the corresponding branch." \
        -m "File **mygentoo:$tag_name** is the custom MKG Docker image built from latest official stage3 and portage archives." \
        -m "To create an updated Gentoo distribution, start a Docker image as indicated in the README.
        -m "You can create an install ISO and a CloneZilla installer medium /dev/sdX by running:" \
        -m "     # mkg $tag_name from_vm vm=name_of_your_VB_machine device_installer ext_device=sdX gentoo.iso"  \
        -m "You can then use this image with a CloneZilla CD to install Gentoo onto any adequate device." \
        "$tag_name"
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
